### ISSUE TITLE
Internationalization Review for VC JSON Schema

### ISSUE THREAD

**Issue by decentralgabe** [w3c/vc-json-schema#164]
This review is for the following specifications: 

- [VC JSON Schema](https://www.w3.org/TR/vc-json-schema/)

1. [x] _If the spec (or its implementation) contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),_ **ensure that there’s metadata about and support for basic things such as language and text direction**.  Also check the detailed guidance for [Language](https://www.w3.org/TR/international-specs/#resource) and [Text direction](https://www.w3.org/TR/international-specs/#text_direction).
  - [ ] Not applicable

JSON Schemas are JSON text intended primarily for machines to read, since they are used for strict static validation of data. Language and text direction concerns are addressed by the noted specification documents for JSON Schema itself. When packaging VC JSON Schemas as verifiable credentials, implementers are encouraged to follow the guidance listed in the [VC Data Model](https://w3c.github.io/vc-data-model/#internationalization-considerations).

2. [ ] _If the spec (or its implementation) allows content authors to produce typographically appealing text, either in its own right, or in association with graphics._ **take into account the different typographic styles used around the world (for things such as line-breaking, text justification, emphasis or other text decorations, text selection and units, etc.)**  Also check the detailed guidance for [Typographic support](https://www.w3.org/TR/international-specs/#typography).
  - [x] Not applicable

This specification is for machine-readable JSON processing without transformation and thus does not provide the features described in the paragraph above.

3. [ ] _If the spec (or its implementation) allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc._ **make allowances for the ways different scripts handle units of text**.  Also check the detailed guidance for [Text-processing](https://www.w3.org/TR/international-specs/#operations).
  - [x] Not applicable

This specification is for machine-readable JSON processing without transformation and thus does not provide the features described in the paragraph above.

4. [x] _If the spec (or its implementation) allows searching or matching of text, including syntax and identifiers_ **understand the implications of normalisation, case folding, etc**.  Also check the detailed guidance for [Text-processing](https://www.w3.org/TR/international-specs/#operations).
  - [ ] Not applicable

Text searching and matching is the primary feature which JSON Schema provides. The documents provided in the specification note JSON Schema language which states this according to a specific version of a JSON Schema specification.

5. [ ] _If the spec (or its implementation) sorts text_ **ensure that it does so in locally relevant ways**. Also check the detailed guidance for [Text-processing](https://www.w3.org/TR/international-specs/#operations).
  - [x] Not applicable

This specification is for machine-readable JSON processing without transformation and thus does not provide the features described in the paragraph above.

6. [ ] _If the spec (or its implementation) captures user input_ **ensure that it also captures metadata about language and text direction, and that it accommodates locale-specific input methods**. 
  - [x] Not applicable

This specification is for machine-readable JSON processing without transformation and thus does not provide the features described in the paragraph above.

7. [ ] _If the spec (or its implementation) deals with time in any way that will be read by humans and/or crosses time zone boundaries_  **ensure that it will represent time as expected in locales around the world, and manage the relationship between local and global/absolute time**. Also check the detailed guidance for [Local dates, times and formats](https://www.w3.org/TR/international-specs/#locale).
  - [x] Not applicable

This specification is for machine-readable JSON processing without transformation and thus does not provide the features described in the paragraph above.

8. [ ] _If the spec (or its implementation) allows any character encoding other than UTF-8._  **make sure you have a convincing argument as to why, and then ensure that the character encoding model is correct**.   Also check the detailed guidance for [Characters](https://www.w3.org/TR/international-specs/#characters).
  - [x] Not applicable

All character encoding for all JSON Schemas, which utilize JSON, use UTF-8 for text encoding.

9. [ ] _If the spec (or its implementation) defines markup_  **ensure support for internationalisation features and avoid putting human-readable text in attribute values or plain-text elements**.  Also check the detailed guidance for [Markup & syntax](https://www.w3.org/TR/international-specs/#markup).
  - [x] Not applicable

This specification is for machine-readable JSON processing without transformation and thus does not provide the features described in the paragraph above.

10. [ ] _If the spec (or its implementation) deals with names, addresses, time & date formats, etc_  **ensure that the model is flexible enough to cope with wide variations in format, levels of data, etc**.   Also check the detailed guidance for [Local dates, times and formats](https://www.w3.org/TR/international-specs/#locale).
  - [x] Not applicable

This specification is for machine-readable JSON processing without transformation and thus does not provide the features described in the paragraph above.

11. [x] _If the spec (or its implementation) describes a format or data that is likely to need localization._  **ensure that there’s an approach in place which allows effective storage and labelling of, and access to localised alternatives for strings, text, images, etc**.  
  - [ ] Not applicable

JSON Schemas, by design, are not intended to be internationalizable, since they are used for strict static validation of data. An implementer may choose to translate a JSON Schema, or make it available in a variety of languages; however, these would be considered distinct JSON Schemas. When packaging VC JSON Schemas as verifiable credentials, implementers are encouraged to follow the guidance listed in the [VC Data Model](https://w3c.github.io/vc-data-model/#internationalization-considerations).

12. [ ] _If the spec (or its implementation) makes any reference to or relies on any cultural norms_  **ensure that it can be adapted to suit different cultural norms around the world (ranging from depictions of people or gestures, to expectations about gender roles, to approaches to work and life, etc)**.
  - [x] Not applicable

This specification is for machine-readable JSON processing without transformation and thus does not provide the features described in the paragraph above.

**Comment by andresuribe87** [comment]
Only one that I'm unsure about is the following. Can you elaborate? 
 

> If the spec (or its implementation) describes a format or data that is likely to need localization. ensure that there’s an approach in place which allows effective storage and labelling of, and access to localised alternatives for strings, text, images, etc.

**Comment by decentralgabe** [comment]
I found this https://github.com/json-schema-org/json-schema-spec/wiki/Localization

**Comment by decentralgabe** [comment]
With #222 the i18n review is complete.
